name: Deploy GitHub Pages

on:
  push:
    branches: [ main, master ]  # Trigger on push to main/master
  workflow_dispatch:           # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Build site
        run: |
          # Add your R commands to build the site here
          # For example, if using pkgdown:
          # Rscript -e 'pkgdown::build_site()'
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # The folder containing your built site
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
